cookbook/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('accounts/signup/', views.signup, name='signup'),
    path('recipes/', views.recipes_index, name='recipes_index'),
    path('recipes/my', views.recipes_user, name='recipes_user'),
    path('recipes/create/', views.RecipeCreate.as_view(), name='recipe_create'),
    path('recipes/<int:recipe_id>/', views.recipe_detail, name='detail'),
    path('recipes/<int:pk>/update/',
         views.RecipeUpdate.as_view(), name='recipe_update'),
    path('recipes/<int:pk>/delete/',
         views.RecipeDelete.as_view(), name='recipe_delete'),
    path('recipes/<int:recipe_id>/add_review/',
         views.add_review, name='add_review'),
    path('recipes/<int:recipe_id>/add_modification/',
         views.add_modification, name='add_modification'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

RATINGS = (
    ('1', '⭐️'),
    ('2', '⭐️⭐️'),
    ('3', '⭐️⭐️⭐️'),
    ('4', '⭐️⭐️⭐️⭐️'),
    ('5', '⭐️⭐️⭐️⭐️⭐️')
)

class Recipe(models.Model):
    name = models.CharField('Recipe Name:', max_length=100)
    ingredients = models.TextField('Ingredients: (comma separate items', max_length=250)
    instructions = models.TextField('Directions: (write complete sentences)', max_length=900)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'recipe_id': self.id})

class Review(models.Model):
    rating = models.CharField(
        max_length=1,
        choices=RATINGS,
        default=RATINGS[0][0]
    )
    comment = models.TextField(max_length=250)

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.comment}"

class Modification(models.Model):
    content = models.TextField(max_length=250)

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.content}"

    

main_app/forms.py
from django.forms import ModelForm
from .models import Review, Modification

class ReviewForm(ModelForm):
  class Meta:
    model = Review
    fields = ['rating', 'comment']

class ModificationForm(ModelForm):
  class Meta:
    model = Modification
    fields = ['content']

main_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Recipe, Review, User
from .forms import ReviewForm, ModificationForm

# Create your views here.


def home(request):
    return render(request, 'home.html')


def recipes_index(request):
    recipes = Recipe.objects.all()
    return render(request, 'recipes/index.html', {'recipes': recipes})


def recipes_user(request):
    recipes = [recipe for recipe in Recipe.objects.all() if recipe.user ==
               request.user]
    return render(request, 'recipes/index.html', {'recipes': recipes})


def recipe_detail(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    items = recipe.ingredients.split(',')
    steps = recipe.instructions.split('.')
    steps.pop()
    review_form = ReviewForm()
    modification_form = ModificationForm()
    return render(request, 'recipes/detail.html', {
        'recipe': recipe,
        'items': items,
        'steps': steps,
        'review_form': review_form,
        'modification_form': modification_form})


def search_results(request):
    return render(request, 'results.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('recipes_index')
        else:
            error_message = 'Invalid sign-up, please try again.'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

# class RecipeCreate(CreateView):
#   model = Recipe
#   fields = '__all__'


class RecipeCreate(LoginRequiredMixin, CreateView):
    model = Recipe
    fields = ['name', 'ingredients', 'instructions']

    def form_valid(self, form):
        # Assign the logged in user
        form.instance.user = self.request.user
        # Let the CreateView do its job as usual
        return super().form_valid(form)


class RecipeUpdate(LoginRequiredMixin, UpdateView):
    model = Recipe
    fields = '__all__'


class RecipeDelete(LoginRequiredMixin, DeleteView):
    model = Recipe
    success_url = '/recipes/'

# @login_required


def add_review(request, recipe_id):
    form = ReviewForm(request.POST)
    if form.is_valid():
        new_review = form.save(commit=False)
        new_review.recipe_id = recipe_id
        new_review.save()
    return redirect('detail', recipe_id=recipe_id)

# @login_required


def add_modification(request, recipe_id):
    form = ModificationForm(request.POST)
    if form.is_valid():
        new_modification = form.save(commit=False)
        new_modification.recipe_id = recipe_id
        new_modification.save()
    return redirect('detail', recipe_id=recipe_id)

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Cooking with BAM</title> 
 {% comment %} This is for the Icon  {% endcomment %}
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'images/icon/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'images/icon/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'images/icon/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'images/icon/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'images/icon/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'images/icon/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'images/icon/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'images/icon/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/icon/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'images/icon/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/icon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'images/icon/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/icon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'images/icon/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">
{% comment %} This for the icon {% endcomment %}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="https://kit.fontawesome.com/0629772919.js" crossorigin="anonymous"></script>
  
  
  {% comment %} initialize {% endcomment %}
  <script>
  
  //Sidenav
    $(document).ready(function(){
        $('.sidenav').sidenav();
    })
  //slider images
   $(document).ready(function(){
    $('.slider').slider();
  });


//dark mode

        
//auto complete 
 $(document).ready(function(){
    $('input.autocomplete').autocomplete({
      data: {
        "Pasta": null,
        "Risoto": null,
        "Chicken Grill": 'https://placehold.it/250x250'
      },
    });
  });
        

  </script>





</head>
<body id="home" class="scrollspy">
  <header>
  <div class="navbar-fixed"> 
    <nav class="grey darken-3" style="padding:0px 10px;">
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="sidenav-trigger" data-target="mobile-nav">
            <i class="material-icons">menu</i>
          </a>
          </li>
          <li><a href="/" class="brand-logo">&nbsp;&nbsp;Cooking with BAM</a></li>
          
        </ul>
        
        <ul class="right hide-on-med-and-down">
            {% if user.is_authenticated %}
            <li>Welcome Chef {{ user }} </li>
            <li><a href="{% url 'recipe_create' %}">Add a Recipe</a></li>
            <li><a href="/recipes/">Community Cookbook</a></li>
            <li><a href="/recipes/my">My Cookbook</a></li>
            <li><a href="/accounts/logout/">Log Out</a></li>
            {% else %}
            <li><a href="/accounts/signup/">Sign Up</a></li>
            <li><a href="/accounts/login/">Log In</a></li>
            {% endif %}
        </ul>
      </div>
    </nav>
</div>

<ul class="sidenav" id="mobile-nav">
             {% if user.is_authenticated %}
            <li><a href="/recipes/">My Cookbook</a></li>
            <li><a href="/accounts/logout/">Log Out</a></li>
            {% else %}
            <li><a href="/accounts/signup/">Sign Up</a></li>
            <li><a href="/accounts/login/">Log In</a></li>
            {% endif %}
</ul>



  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
    
  </main>
  <footer class="page-footer">
    <div  class= "grey darken-3"  style="padding:16px 15px; text-align:right"  >All Rights Reserved, &copy; 2020 Cooking with BAM &nbsp;
  
  
  
   <a  href="https://www.facebook.com/profile.php?id=100052946640434&sk=timeline#_" target="_blank" class= "left" "white-text">
        <i class="fab fa-facebook fa-2x" style="padding:4px  height:50  "  >&nbsp</i>
        </a>
        
        <a  href="https://www.instagram.com/bamrecipes/" target="_blank" class= "left" "white-text"  >
        <i class="fa fa-instagram fa-2x" style="wight:20 height:50    "   >&nbsp</i>
        </a>


        <a href="https://github.com/BSacco0674/cookbook" target="_blank" class= "left" "white-text">
        <i class="fa fa-github fa-2x" style="padding:4px  height:50  "  >&nbsp</i>
        </a>

  </div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}

<html class="home-bg">



<div class="slider">
    <ul class="slides">
      <li>
        <img src="https://images.pexels.com/photos/1407857/pexels-photo-1407857.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260" > <!-- random image -->
        <div class="caption center-align">
          <h3>Welcome to BAM!</h3>
          <h5 class="light grey-text text-lighten-3">A community cookbook filled with user-based recipes</h5>
        </div>
      </li>
      <li>
        <img src="https://images.pexels.com/photos/3979423/pexels-photo-3979423.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"> <!-- random image -->
        <div class="caption left-align">
          <h3 style="color:black" position="bottom">Try our best recipes!</h3>
          <h5 style="color:black" class="light black-text text-lighten-1"> See Creators' recipes below.</h5>
        </div>
      </li>
      <li>
        <img src="https://images.pexels.com/photos/1660030/pexels-photo-1660030.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260"> <!-- random image -->
        <div class="caption right-align ">
          <h3 style="color:black" position="bottom">Stay Healthy</h3>
          <h5 style="color:black" class="light black-text text-lighten-1">Eat Healthy and enjoy the food!</h5>
        </div>
      </li>
      <li>
        <img src="https://media.giphy.com/media/2xPS9bJpkDXWvgcW4L/giphy.gif"> <!-- random image -->
        <div class="caption center-align">
          <h3 class="slider-headline" style="color:black" position="bottom">  Feel like a chef with BAM!!!!!</h3>
        </div>
      </li>
    </ul>
  </div>



<!--Code for future API Field
{% comment %} Search area {% endcomment %}
<section id="search" class="section section-search black white-text 
center scrollspy">
<div class="container">
    <div class="row">
        <div class="col s12">
            <h4>Search for Recipes </h4>
            <div class="input-field">
                <input type="text" class="white grey-text autocomplete" id="autocomplete-input" placeholder="Find the most delicious recipe here!">
                <input class="btn btn-default" type="submit" value="Submit">
                </div>
            </div>
        </div>
    </div>
 </section> -->
 <br>
{% comment %} section favorite food {% endcomment %}

  <section id="popular" class="section section-popular scrollspy">
    <div class="container">
      <div class="row">
        <h4 class="center">BAM's
          <span class="teal-text">Favorite</span> Recipes</h4>
          <a href="https://cooking-with-bam.herokuapp.com/recipes/4/">
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <img src="https://images.pexels.com/photos/106343/pexels-photo-106343.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="Image" height="150" width="42">
              <span class="card-title"></span>
            </div>
            <div class="card-content" "text-align:center" >
              <h6 style="color:black">Alfonso's Roasted Chicken 
              </h6>
            </div>
          </div>
        </div>
          </a>
          <a href="https://cooking-with-bam.herokuapp.com/recipes/6/">
        <div class="col s12 m4">
          <div class="card">
            <div class="card-image">
              <img src="https://www.momontimeout.com/wp-content/uploads/2018/10/homemade-mac-and-cheese-recipe-titled-500x375.jpg" alt="Image" height="150" width="42">
              <span class="card-title"></span>
            </div>
            <div class="card-content" "text-align:center">
             <h6 style="color:black"> Matty's Mac & Cheese
              </h6>
            </div>
          </div>
        </div>
        </a>
          <a href="https://cooking-with-bam.herokuapp.com/recipes/15/"> 
        <div class="col s12 m4">
            <div class="card">
              <div class="card-image">
                <img src="https://assets.bonappetit.com/photos/57acf62a53e63daf11a4dbee/master/pass/best-ever-grilled-cheese.jpg" alt="Image" height="150" width="42">
                <span class="card-title"></span>
              </div>
              <div class="card-content" "text-align:center">
                <h6 style="color:black"> Brandon's Grilled Cheese</h6>
              </div>
            </div>
        </div>
          </a>
      </div>
      
      </div>
    </div>
  </section>



  
{% endblock %}

main_app/templates/main_app/recipe_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

<html class="delete-bg">

<div class="slider">
    <ul class="slides">
      <li>
        <img src="https://media1.giphy.com/media/SVHVfHH7CvuneydXdB/giphy.gif?cid=ecf05e476fdab65d073f10d31e7e7ef91dc9f73824b7e7b0&rid=giphy.gif" > <!-- random image -->
        <div class="caption center-align">
         <h1>Delete Recipe</h1>

  <h4>Are you sure you want to delete {{ recipe.name }}?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn">
    <a class="btn" href="{% url 'detail' recipe.id %}">Cancel</a>
  </form>
        </div>
      </li>
      </div>
  
{% endblock %}

main_app/templates/main_app/recipe_form.html
{% extends 'base.html' %}
{% block content %}
    {% if recipe %}
        <h1>Edit {{ recipe.name }}</h1>
    {% else %}
        <h1>Add New Recipe</h1>
    {% endif %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_p }}
        </table>
        {% if recipe %}
            <input type="submit" value="Save Recipe" class="btn">
        {% else %}
            <input type="submit" value="Add Recipe" class="btn">
        {% endif %}
    </form>
{% endblock %}

main_app/templates/recipes.html
{% block content %}

<h1>Recipe List</h1>

{% endblock %}

main_app/templates/recipes/detail.html
{% extends 'base.html' %}

{% block content %}


<html class="detail-recipe-bg">

<h1>{{ recipe.name }}</h1>

<div class="card">
  <div class="card-content grey darken-3">
    <div class="row">
      <div class="ingredients col s4">
        <h6><strong>Ingredients:</strong></h6><hr>
        {% for item in items %}
          <p>{{ item }}</p>
        {% endfor %}
      </div>
      <div class="directions col s4">
        <h6><strong>Directions:</strong></h6><hr>
        <ol>
          {% for step in steps %}
            <li>{{ step }}.</li>
          {% endfor %}
      </ol>
      </div>
      <div class="col s4">
        <h6>Add Review:</h6>
        <form action="{% url 'add_review' recipe.id %}" method="post">
          {% csrf_token %}
          {{ review_form.as_p }}
          <input type="submit" class="btn" value="Add Review">
        </form>
        <br><br>
        <h6>Add Modification:</h6>
        <form action="{% url 'add_modification' recipe.id %}" method="post">
          {% csrf_token %}
          {{ modification_form.as_p }}
          <input type="submit" class="btn" value="Add Modification">
        </form>
      </div>
    </div>
  </div>
  {% if user.id == recipe.user_id %}
  <div class="card-action">
    <a class="btn" href="{% url 'recipe_update' recipe.id %}">Edit</a>
    <a class="btn" href="{% url 'recipe_delete' recipe.id %}">Delete</a>
  </div>
  {% endif %}
</div>
<div class="row">
  <div class="col s6">
    <h5>Reviews:</h5>
    <div class="card">
      <div class="card-content">
        {% for review in recipe.review_set.all %}
        <p>{{ review.rating }}/5 stars ~ {{ review.comment }}</p>
      {% endfor %}
      </div>
    </div>
  </div>
  <div class="col s6">
    <h5>Modifications:</h5>
    <div class="card">
      <div class="card-content">
        {% for modification in recipe.modification_set.all %}
        <p>{{ modification.content }}</p>
      {% endfor %}
      </div>
    </div>
  </div>
</div>
<script>
  var selectEl = document.getElementById('id_rating');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/recipes/index.html
{% extends 'base.html' %}

{% block content %}

<html class="index-bg">





{% for recipe in recipes %}
  <div class="row">
    <a href="{% url 'detail' recipe.id %}">
        <div class="col s2 m4">
        <div class="card-panel grey darken-3">
        <span style="color:white" class="card-title">{{ recipe.name }}</span>
        </div>
    </a>
  </div>


<script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.6/lib/darkmode-js.min.js"></script>
<script>

var options = {
  bottom: '350px', // default: '32px'
  right: 'unset', // default: '32px'
  left: '10px', // default: 'unset'
  time: '0.5s', // default: '0.3s'
  mixColor: '#fff', // default: '#fff'
  backgroundColor: "#fff url('https://images.pexels.com/photos/1660030/pexels-photo-1660030.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260') ",  // default: '#fff'
  buttonColorDark: '#100f2c',  // default: '#100f2c'
  buttonColorLight: "#fff", // default: '#fff'
  saveInCookies: false, // default: true,
  label: '🌓', // default: ''
  autoMatchOsTheme: true // default: true
}

const darkmode = new Darkmode(options);
darkmode.showWidget();

</script>


{% endfor %}

{% endblock %}

main_app/templates/results.html
{% extends 'base.html' %}

{% block content %}

<h1>Search Page</h1>
<a href="/detail/">Test Recipe</a>

{% endblock %}

main_app/templates/search.html
{% extends 'base.html' %}

{% block content %}

<h1>Search Page</h1>
<a href="/detail/">Test Recipe</a>

{% endblock %}